# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PrivateFolders\Desktop\Nativefier_GUI\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BodyLabel = BodyLabel(Form)
        self.BodyLabel.setText("")
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout.addWidget(self.BodyLabel)
        self.TitleLabel = TitleLabel(Form)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.LineEdit = LineEdit(Form)
        self.LineEdit.setObjectName("LineEdit")
        self.verticalLayout.addWidget(self.LineEdit)
        self.TitleLabel_2 = TitleLabel(Form)
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.verticalLayout.addWidget(self.TitleLabel_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LineEdit_2 = LineEdit(Form)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.horizontalLayout.addWidget(self.LineEdit_2)
        self.PrimaryPushButton_2 = PrimaryPushButton(Form)
        self.PrimaryPushButton_2.setObjectName("PrimaryPushButton_2")
        self.horizontalLayout.addWidget(self.PrimaryPushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.PrimaryPushButton = PrimaryPushButton(Form)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.verticalLayout.addWidget(self.PrimaryPushButton)
        self.HyperlinkButton = HyperlinkButton(Form)
        self.HyperlinkButton.setUrl(QtCore.QUrl("https://github.com/NulConst/Nativefier_GUI"))
        self.HyperlinkButton.setObjectName("HyperlinkButton")
        self.verticalLayout.addWidget(self.HyperlinkButton)
        self.HyperlinkButton_2 = HyperlinkButton(Form)
        self.HyperlinkButton_2.setUrl(QtCore.QUrl("https://space.bilibili.com/2006869246"))
        self.HyperlinkButton_2.setObjectName("HyperlinkButton_2")
        self.verticalLayout.addWidget(self.HyperlinkButton_2)

        self.retranslateUi(Form)
        self.PrimaryPushButton.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "Electron镜像源"))
        self.TitleLabel_2.setText(_translate("Form", "NPM镜像源"))
        self.PrimaryPushButton_2.setText(_translate("Form", "确定"))
        self.PrimaryPushButton.setText(_translate("Form", "返回"))
        self.HyperlinkButton.setText(_translate("Form", "项目地址"))
        self.HyperlinkButton_2.setText(_translate("Form", "作者B站"))
from qfluentwidgets import BodyLabel, HyperlinkButton, LineEdit, PrimaryPushButton, TitleLabel
import Main_rc
